name: GriefNotify
version: '1.0-SNAPSHOT'
main: org.makarfp.griefnotify.GriefNotify
api-version: '1.21'
commands:
  griefnotify:
    description: Включение или отключение уведомлений о гриферстве
    usage: /griefnotify
    permission: griefnotify.use
    permission-message: У вас нет прав для этой команды.
